### ISSUE TITLE
couldn't find "libopencv_java4.so"

### ISSUE THREAD

**Issue by dhvani023** [chaits98/ocr-android#1]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.extempo.typescan-1/base.apk"],nativeLibraryDirectories=[/data/app/com.extempo.typescan-1/lib/arm64, /data/app/com.extempo.typescan-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libopencv_java4.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at com.extempo.typescan.utilities.ModuleLoader.load(ModuleLoader.kt:12)
        at com.extempo.typescan.view.HomeActivity.<clinit>(HomeActivity.kt:112)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1079)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2615)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by chaits98** [comment]
@dhvani023 Please take pull from master and try again, I have added link to opencv sdk zip file as well.

**Comment by SaaifKhan** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.extempo.typescan-1/base.apk"],nativeLibraryDirectories=[/data/app/com.extempo.typescan-1/lib/arm64, /data/app/com.extempo.typescan-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libopencv_java3.so"

**Comment by chaits98** [comment]
@saiif12 please follow the steps mentioned in readme.md file
