### ISSUE TITLE
Tried cloning it and running but crashes leaving a UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Khali851999** [chaits98/ocr-android#2]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.extempo.typescan, PID: 19588
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.extempo.typescan-dO9laIeujeeUWrmQvb3M2w==/base.apk"],nativeLibraryDirectories=[/data/app/com.extempo.typescan-dO9laIeujeeUWrmQvb3M2w==/lib/arm64, /data/app/com.extempo.typescan-dO9laIeujeeUWrmQvb3M2w==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]] couldn't find "libopencv_java3.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.extempo.typescan.utilities.ModuleLoader.load(ModuleLoader.kt:12)
        at com.extempo.typescan.view.HomeActivity.<clinit>(HomeActivity.kt:112)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3535)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
I/Process: Sending signal. PID: 19588 SIG: 9

**Comment by Khali851999** [comment]
Is there something that is problematic on my end? I wanted to use the same functionality, maybe you could help?

**Comment by chaits98** [comment]
Yes, please check the libopencv_java3.so binary in libs folder [Please add this file if not already done], this is happening because this file cannot be found.

**Comment by Khali851999** [comment]
Yes, but I cloned the project as it is, and cannot locatie the file in the github project as well. Can you link the file if already present?

**Comment by chaits98** [comment]
Please follow the instructions on Get Started section.

**Comment by Khali851999** [comment]
thanks, works
